const { Router } = require('express');

const authRoutes = require('./auth.routes');
const usuarioRoutes = require('./usuario.routes');
const rolRoutes = require('./rol.routes');
const temporadaRoutes = require('./temporada.routes');
const lugarRoutes = require('./lugar.routes');
const tituloRoutes = require('./titulo.routes');
const divisionRoutes = require('./division.routes');
const delegadoRoutes = require('./delegado.routes');
const seccionRoutes = require('./seccion.routes');
const categoriaRoutes = require('./categoria.routes');
const jugadorRoutes = require('./jugador.routes');
const entrenadorRoutes = require('./entrenador.routes');
const entrenamientoRoutes = require('./entrenamiento.routes');
const partidoRoutes = require('./partido.routes');
const equipoRoutes = require('./equipo.routes');
const incidenciaRoutes = require('./incidencia.routes');
const resultadoRoutes = require('./resultado.routes');
const calendarioRoutes = require('./calendario.routes');
const entrenamientoJugadorRoutes = require('./entrenamientoJugador.routes');
const partidoJugadorRoutes = require('./partidoJugador.routes');
const tipofutbolRoutes = require('./tipofutbol.routes');
const utilRoutes = require('./util.routes');

const router = Router();

router.use('/auth', authRoutes);
router.use('/usuarios', usuarioRoutes);
router.use('/roles', rolRoutes);
router.use('/temporadas', temporadaRoutes);
router.use('/lugares', lugarRoutes);
router.use('/titulos', tituloRoutes);
router.use('/divisiones', divisionRoutes);
router.use('/delegados', delegadoRoutes);
router.use('/secciones', seccionRoutes);
router.use('/categorias', categoriaRoutes);
router.use('/jugadores', jugadorRoutes);
router.use('/entrenadores', entrenadorRoutes);
router.use('/entrenamientos', entrenamientoRoutes);
router.use('/partidos', partidoRoutes);
router.use('/equipos', equipoRoutes);
router.use('/incidencias', incidenciaRoutes);
router.use('/resultados', resultadoRoutes);
router.use('/calendario', calendarioRoutes);
router.use('/entrenamientos-jugadores', entrenamientoJugadorRoutes);
router.use('/partidos-jugadores', partidoJugadorRoutes);
router.use('/tipos-futbol', tipofutbolRoutes);
router.use('/util', utilRoutes);

module.exports = router;
