const { Router } = require('express');

const authRoutes = require('./auth.routes');
const usuarioRoutes = require('./usuario.routes');
const temporadaRoutes = require('./temporada.routes');
const lugarRoutes = require('./lugar.routes');
const tituloRoutes = require('./titulo.routes');
const divisionRoutes = require('./division.routes');
const posicionRoutes = require('./posicion.routes');
const delegadoRoutes = require('./delegado.routes');
const seccionRoutes = require('./seccion.routes');
const categoriaRoutes = require('./categoria.routes');
const jugadorRoutes = require('./jugador.routes');
const entrenadorRoutes = require('./entrenador.routes');
const entrenamientoRoutes = require('./entrenamiento.routes');
const partidoRoutes = require('./partido.routes');
const equipoRoutes = require('./equipo.routes');
const resultadoRoutes = require('./resultado.routes');
const calendarioRoutes = require('./calendario.routes');
const entrenamientoJugadorRoutes = require('./entrenamientoJugador.routes');
const tipofutbolRoutes = require('./tipofutbol.routes');
const utilRoutes = require('./util.routes');
const patrocinadorRoutes = require('./patrocinador.routes');
const categoriaCalendarioRoutes = require('./jornada.routes');
const sancionRoutes = require('./sancion.routes');
const plantillaRoutes = require('./plantilla.routes');
const importRoutes = require('./import.routes');
const cambioRoutes = require('./cambio.routes');
const equipoJugadorRoutes = require('./equipoJugador.routes');
const promocionRoutes = require('./promocion.routes');

const router = Router();

router.use('/auth', authRoutes);
router.use('/usuarios', usuarioRoutes);
router.use('/temporadas', temporadaRoutes);
router.use('/lugares', lugarRoutes);
router.use('/titulos', tituloRoutes);
router.use('/divisiones', divisionRoutes);
router.use('/posiciones', posicionRoutes);
router.use('/delegados', delegadoRoutes);
router.use('/secciones', seccionRoutes);
router.use('/categorias', categoriaRoutes);
router.use('/jugadores', jugadorRoutes);
router.use('/entrenadores', entrenadorRoutes);
router.use('/entrenamientos', entrenamientoRoutes);
router.use('/partidos', partidoRoutes);
router.use('/equipos', equipoRoutes);
router.use('/resultados', resultadoRoutes);
router.use('/calendario', calendarioRoutes);
router.use('/entrenamientos-jugadores', entrenamientoJugadorRoutes);
router.use('/tipos-futbol', tipofutbolRoutes);
router.use('/patrocinadores', patrocinadorRoutes);
router.use('/jornadas', categoriaCalendarioRoutes);
router.use('/sanciones', sancionRoutes);
router.use('/plantillas', plantillaRoutes);
router.use('/import', importRoutes);
router.use('/util', utilRoutes);
router.use('/cambios', cambioRoutes);
router.use('/equipos-jugadores', equipoJugadorRoutes);
router.use('/promociones', promocionRoutes);

module.exports = router;
